### ISSUE TITLE
API Disconnect spam on ESPHome 2026.4.0

### ISSUE THREAD

**Issue by nlowe** [Ylianst/ESP-IQ2020#90]
This is more of an FYI, as this is a problem on the ESPHome side. See the following issues for details:

* esphome/esphome#15824
* esphome/aioesphomeapi#1590

It looks like it'll be fixed in 2026.4.1. I'm making an issue here so others don't have to go hunting for it, feel free to close it if you'd like!

After upgrading to ESPHome 2026.4.0 and pushing an update, the log viewer spams this in a loop:

```
INFO ESPHome 2026.4.0
INFO Reading configuration /data/hot-tub.yaml...
INFO Detected timezone 'Etc/UTC'
INFO Starting log output from 10.69.245.254 using esphome API
INFO Successfully resolved hot-tub @ 10.69.245.254 in 0.000s
INFO Successfully connected to hot-tub @ 10.69.245.254 in 0.078s
INFO Successful handshake with hot-tub @ 10.69.245.254 in 0.066s
[19:59:41.209][I][app:141]: ESPHome version 2026.4.0 compiled on 2026-04-19 19:57:02 +0000
[19:59:41.209][I][app:148]: ESP32 Chip: ESP32 rev1.1, 2 core(s)
[19:59:41.209][W][app:188]: Bootloader supports SRAM1 as IRAM (+40KB). Set sram1_as_iram: true under esp32 > framework > advanced
[19:59:41.342][S][number]: 'Salt System Power' >> 8.00
ERROR Fatal error: protocol.data_received() call failed.
protocol: <aioesphomeapi._frame_helper.noise.APINoiseFrameHelper object at 0x7b1ffa476e00>
transport: <_SelectorSocketTransport fd=12 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1027, in _read_ready__data_received
    self._protocol.data_received(data)
  File "aioesphomeapi/_frame_helper/noise.py", line 112, in aioesphomeapi._frame_helper.noise.APINoiseFrameHelper.data_received
  File "aioesphomeapi/_frame_helper/noise.py", line 148, in aioesphomeapi._frame_helper.noise.APINoiseFrameHelper.data_received
  File "aioesphomeapi/_frame_helper/noise.py", line 335, in aioesphomeapi._frame_helper.noise.APINoiseFrameHelper._handle_frame
  File "aioesphomeapi/connection.py", line 1104, in aioesphomeapi.connection.APIConnection.process_packet
  File "aioesphomeapi/client_base.py", line 76, in aioesphomeapi.client_base.on_state_msg
  File "/usr/local/lib/python3.12/site-packages/aioesphomeapi/log_runner.py", line 125, in on_state
    text = format_state_log(state, info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aioesphomeapi/state_log_formatter.py", line 334, in format_state_log
    return formatter(state, info)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aioesphomeapi/state_log_formatter.py", line 81, in _format_sensor
    decimals = max(0, info.accuracy_decimals)
                      ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NumberInfo' object has no attribute 'accuracy_decimals'
INFO Processing unexpected disconnect from ESPHome API for hot-tub @ 10.69.245.254
WARNING Disconnected from API
```

Looking at the linked issues for ESPHome, this is just a web / log artifact. The actual device is not resetting.

**Comment by nlowe** [comment]
Just checking back in after upgrading ESPHome to 2026.4.2, I can confirm the problem is indeed resolved.
