### ISSUE TITLE
Fails to compile with ESPHome 2026.1

### ISSUE THREAD

**Issue by sigmabeta** [Ylianst/ESP-IQ2020#83]
Fails consistently with error:

```
Compiling .pioenvs/backyard-hot-tub/src/esphome/components/wifi_signal/wifi_signal_sensor.cpp.o
src/esphome/components/iq2020/iq2020.cpp: In member function 'void IQ2020Component::accept()':
src/esphome/components/iq2020/iq2020.cpp:203:53: error: no matching function for call to 'esphome::socket::Socket::getpeername()'
  203 |         std::string identifier = socket->getpeername();
      |                                  ~~~~~~~~~~~~~~~~~~~^~
In file included from src/esphome/components/iq2020/iq2020.h:3,
                 from src/esphome/components/iq2020/iq2020.cpp:1:
src/esphome/components/socket/socket.h:43:15: note: candidate: 'virtual int esphome::socket::Socket::getpeername(sockaddr*, socklen_t*)'
   43 |   virtual int getpeername(struct sockaddr *addr, socklen_t *addrlen) = 0;
      |               ^~~~~~~~~~~
src/esphome/components/socket/socket.h:43:15: note:   candidate expects 2 arguments, 0 provided
Compiling .pioenvs/backyard-hot-tub/src/esphome/core/application.cpp.o
Compiling .pioenvs/backyard-hot-tub/src/esphome/core/color.cpp.o
*** [.pioenvs/backyard-hot-tub/src/esphome/components/iq2020/iq2020.cpp.o] Error 1```

**Comment by Ylianst** [comment]
@sigmabeta - No worries. Thanks for taking the time to report, it's much appreciated.
